[defaults]
app_name = "Example Wizard"
backend_port = 5001
backend_url = "127.0.0.1"
copyright = "By: slopez"
debug = true
high_resolution = false
main_title = "Amazing Toolkit Wizard"
theme = "ansys_light.json"
toolkit_name = "example"
welcome_message = "Welcome to the amazing toolkit"
year = 2026

[[defaults.add_left_menus]]
btn_icon = "icon_home.svg"
btn_id = "home_menu"
btn_text = "Home"
btn_tooltip = "Home"
is_active = false
show_top = true

[[defaults.add_left_menus]]
btn_icon = "icon_plot_3d.svg"
btn_id = "geometry_menu"
btn_text = "Primitives Builder"
btn_tooltip = "Builder"
is_active = false
show_top = true

[[defaults.add_left_menus]]
btn_icon = "icon_plot_2d.svg"
btn_id = "plot_design_menu"
btn_text = "Plot Design"
btn_tooltip = "Design"
is_active = false
show_top = true

[[defaults.add_left_menus]]
btn_icon = "help.svg"
btn_id = "help_menu"
btn_text = "Help"
btn_tooltip = "Help"
is_active = false
show_top = false

[[defaults.add_left_menus]]
btn_icon = "icon_log.svg"
btn_id = "progress_menu"
btn_text = "Progress"
btn_tooltip = "Progress"
is_active = false
show_top = false

[example]
primitives_created = []
