aedt_version= "2025.2"
non_graphical= true
active_project= ""
active_design= ""
project_list= []
design_list= {}
selected_process= 0
use_grpc= true
is_toolkit_busy= false
url= "127.0.0.1"
port= 5001
debug= false
toolkit_name= "common"
log_file= "common_backend.log"
state = ""
progress = 0
